In [3]:
from sqlalchemy import create_engine
import pandas as pd

In [7]:
engine = create_engine("mysql+pymysql://root:teamlab2016@ortega@192.9.64.15/trademarks")

In [9]:
df = pd.read_sql("select * from Images limit 10", con=engine)

In [10]:
df

,TrademarkKey,viennaCode,appReferenceNumber,applicationNumber,SourceImage,TargetImage,RejectDecision
0,1,050519 050520 050521,4020107009967,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
1,2,,4020107001276,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
2,3,,4020177005758,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
3,4,,4020187016370,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
4,5,,4020067002628,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
5,6,,4020067004760,,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
6,7,,,4019500000040,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
7,8,,,4019500000034,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
8,9,,,4019500000037,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAA...,,
9,10,,,4019500000039,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...,,